some updates for peco

diff --git a/bash/bashrc b/bash/bashrc
--- a/bash/bashrc
+++ b/bash/bashrc
@@ -21,19 +21,27 @@ fi
 export LANG=en_US.UTF-8
 
 #
+# aliases
+#
+alias man='LANG=ja_JP.utf8 man'
+alias grep='grep --color=auto'
+alias fgrep='fgrep --color=auto'
+alias egrep='egrep --color=auto'
+alias ls='ls --color=auto'
+alias tm='tmux -2u a || tmux -2u'
+type gsed > /dev/null 2>&1 && alias sed='gsed'
+
+#
 # functions
 #
 function addpath(){
-	if [ ! -d ${1} ]; then
-		echo "[addpath] ${1} does not exist."
+	[ -d ${1} ] || { echo "[addpath] ${1} does not exist."; return; }
+	if [ "${2}" == "man" ]; then
+		# for MANPATH
+		export MANPATH=${1}:${MANPATH//$1:/}
 	else
-		if [ "${2}" == "man" ]; then
-			# for MANPATH
-			export MANPATH=${1}:${MANPATH//$1:/}
-		else
-			# for PATH
-			export PATH=${1}:${PATH//$1:/}
-		fi
+		# for PATH
+		export PATH=${1}:${PATH//$1:/}
 	fi
 }
 
@@ -46,36 +54,30 @@ function check_cmd(){
 	type ${1} > /dev/null 2>&1 || { echo "${1} is not installed"; return 1; }
 }
 
-#http://weblog.bulknews.net/post/89635306479/ghq-peco-percol
-function peco-src () {
-	check_cmd "peco" || return
-	check_cmd "ghq" || return
-
-	local selected_dir=$(ghq list -p | peco)
-	if [ -n "$selected_dir" ]; then
-		cd ${selected_dir}
-	fi
-}
-
-bind '"\C-]":"peco-src\n"'
-
-peco-run-cmd(){
+function peco-run-cmd(){
 	if [ -n "$1" ] ; then
-		# Replace the last entry, "peco-history", with $1
+		# Replace the last entry, with $1
 		history -s $1
 		echo $1 >&2
 		# Uncomment below to execute it here directly
 		eval $1
 	else
-		# Remove the last entry, "peco-history"
+		# Remove the last entry
 		history -d $((HISTCMD-1))
 	fi
 }
 
-# http://qiita.com/yungsang/items/09890a06d204bf398eea
-peco-history() {
+function peco-src () {
 	check_cmd "peco" || return
+	check_cmd "ghq" || return
+	local CMD=$(echo $(ghq list -p | peco) | sed -e 's/^/cd /g')
+	peco-run-cmd "$CMD"
+}
 
+bind '"\C-]":"peco-src\n"'
+
+function peco-history() {
+	check_cmd "peco" || return
 	local NUM=$(history | wc -l)
 	local FIRST=$((-1*(NUM-1)))
 
@@ -85,36 +87,22 @@ peco-history() {
 		echo "No history" >&2
 		return
 	fi
-
 	local CMD=$(fc -l $FIRST | sort -k 2 -k 1nr | uniq -f 1 | sort -nr | sed -E 's/^[0-9]+//' | peco | head -n 1)
-
 	peco-run-cmd "$CMD"
 }
 
 bind '"\C-r":"peco-history\n"'
 
-# http://blog.glidenote.com/blog/2014/06/26/snippets-peco-percol/
-peco-snippets() {
+function peco-snippets() {
 	check_cmd "peco" || return
-	[ ! -f $HOME/.snippets ] && { echo "Couldn't find ~/.snippets"; return; }
-	local CMD=$(grep -v "^#" ~/.snippets | peco)
+	[ -f $HOME/.snippets ] || { echo "Couldn't find ~/.snippets"; return; }
+	local CMD=$(grep -v "^#" ~/.snippets | sed '/^$/d' | peco)
 	peco-run-cmd "$CMD"
 }
 
 stty quit undef
 bind '"\C-\\":"peco-snippets\n"'
 
-
-#
-# aliases
-#
-alias man='LANG=ja_JP.utf8 man'
-alias grep='grep --color=auto'
-alias fgrep='fgrep --color=auto'
-alias egrep='egrep --color=auto'
-alias ls='ls --color=auto'
-alias tm='tmux -2u a || tmux -2u'
-alias ghs='cd $(ghq list -p | peco)'
 
 #
 # append to the history file, don't overwrite it
@@ -193,9 +181,7 @@ psone(){
 	local BRANCH=111
 	
 	# load color config if exists
-	if [ -f $HOME/.bash_color ]; then
-		. $HOME/.bash_color
-	fi
+	[ -f $HOME/.bash_color ] && . $HOME/.bash_color
 
 	GIT_PS1_SHOWDIRTYSTATE=true
 	
